name: Test runner
run-name: ${{ github.actor }} is test runner
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy: # Это стратегия запусков
      matrix: # Запускать это задание с разными параметрами
        node-version: [18.x] # Версии ноды
    steps:
      - uses: actions/checkout@v1 
      - name: Use Node.js ${{ matrix.node-version }} # Установим ноду
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Test
        run: |
          npm run test:coverage